# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: do-snapshot-pruner
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: build
    ldflags:
      - -X github.com/brpaz/do-snapshot-pruner/cmd.buildVersion={{.Version}}
      - -X github.com/brpaz/do-snapshot-pruner/cmd.buildCommit={{.FullCommit}}
      - -X github.com/brpaz/do-snapshot-pruner/cmd.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz

nfpms:
  - id: default
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: Bruno Paz <oss@brunopaz.net>
    description: Command Line tool to automatically delete old volume snapshots on DigitalOcean
    license: MIT
    formats:
      - deb
      - rpm

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - do-snapshot-pruner
    image_templates:
      - "brpaz/do-snapshot-pruner:latest"
      - "brpaz/do-snapshot-pruner:{{ .Tag }}"
    dockerfile: Dockerfile.realease
    build_flag_templates:
      - "--pull"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=VCF_REF={{.FullCommit}}"
      - "--build-arg=VERSION={{.Version}}"
