name: CI

# This workflow will run on master branch and on any pull requests targeting master
on:
  push:
  pull_request:

jobs:
  lint-go:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint Go Code
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |sudo  sh -s -- -b /usr/local/bin v1.25.0
          golang-ci run . -v

  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Tests
        run: make test-coverage

      # - name: Upload Coverage report to Codacy
      #   run: |
      #     export PATH=$PATH:$(go env GOPATH)/bin
      #     go get github.com/schrej/godacov
      #     godacov -t $CODACY_TOKEN -r ./coverage/cover.out -c $GITHUB_SHA
      #   env:
      #     CODACY_TOKEN: ${{secrets.CODACY_TOKEN}}
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/integration' && github.event_name == 'push'
    needs: [lint-go, test-unit]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Bump version and Generate Changelog
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          npx standard-version -no-verify
          git remote rm origin
          git remote add origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git push --follow-tags origin HEAD:master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_ACTOR: ${{github.actor}}
          GITHUB_REPOSITORY: ${{github.repository}}
